#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-dom4j
Version  : 1.1
Release  : 1
URL      : https://github.com/dom4j/dom4j/archive/dom4j-1-1.tar.gz
Source0  : https://github.com/dom4j/dom4j/archive/dom4j-1-1.tar.gz
Source1  : https://repo1.maven.org/maven2/dom4j/dom4j/1.1/dom4j-1.1.jar
Source2  : https://repo1.maven.org/maven2/dom4j/dom4j/1.1/dom4j-1.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause Plexus
Requires: mvn-dom4j-data = %{version}-%{release}

%description
These are XSL stylesheets for the DocBk XML DTD. (They would
also work for the DocBook DTD, modulo certain namecase problems
and the fact that there aren't (yet) any XSL implementations
that work with SGML source documents.)

%package data
Summary: data components for the mvn-dom4j package.
Group: Data

%description data
data components for the mvn-dom4j package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/dom4j/dom4j/1.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/dom4j/dom4j/1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/dom4j/dom4j/1.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/dom4j/dom4j/1.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/dom4j/dom4j/1.1/dom4j-1.1.jar
/usr/share/java/.m2/repository/dom4j/dom4j/1.1/dom4j-1.1.pom
